import Head from "next/head";
import {
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import saludo from "../public/dev-ed-wave.png";
import Image from "next/image";
import springBoot from "../public/spring_boot_logo.png"
import kotlinLogo from "../public/kotlin-2-logo.png"
import sqlLogo from "../public/sql-logo.png"
import reactLogo from "../public/react-logo.png";
import graphLogo from "../public/graph-logo.png"
import tailwindLogo from "../public/tailwind-logo.png"
import postgreLogo from "../public/postgre-logo.png"
import denoLogo from "../public/denox-logo.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portafolio Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Desarrollo Web II</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Sebastián Herrera
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Portafolio Web
            </h3>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/Sebas0306?tab=repositories" target="_blank"><AiFillGithub /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={saludo} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Datos personales</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Soy estudiante de la <span className="text-teal-500">Universidad de la Costa</span>, actualmente me encuentro
              en 8vo semestre de ingeniería de sistemas. Soy orgullosamente isleño, nací  y viví gran parte de mi vida en <span className="text-teal-500">San Andrés Islas</span>.
              Actualmente tengo 20 años. Como pasatiempos favoritos tengo: ir al gimnasio, jugar videojuegos, bucear. 
            </p>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Perfil profesional</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Me caracterizo por ser una persona con buenas habilidades blandas, tales como: buena comunicación, capacidad de adaptabilidad,
              capacidad de líder, gran disponibilidad a aprender.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Por parte de mis habilidad robustas, estos son mis conocimientos:
            </p>
          </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 mr-20 justify-items-center">
              <div className="lg:flex gap-10 flex-wrap">
              <Image src={reactLogo} width={100} height={90}/>
              <Image src={springBoot} width={150} height={100} />
              <Image src={kotlinLogo} width={100} height={100} />
              <Image src={sqlLogo} width={100} height={100} />
              <Image src={graphLogo} width={220} height={100} />
              <Image src={postgreLogo} width={200} height={100} />
              <Image src={tailwindLogo} width={200} height={100} />
              <Image src={denoLogo} width={250} height={100} />
              </div>
            </div>     
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Experiencia profesional</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Actualmente no cuento con experiencia profesional, pero me encuentro como trainee en una empresa que brinda un
              software de manejo contable llamada <a href="https://www.qtsolutions.com.co/"  target= "_blank"><span className="text-teal-500">QualityTech Solutions</span></a>.

            </p>
          </div>
        </section>
        <section className="pb-40">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Experiencia académica</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Mi experiencia académica ha sido bastante buena, he aprendido no solo a programar sino a tener una vista más general
              de todo lo que un ingeniero de sistemas puede hacer. Actualmente me encuentro haciendo una tesis en la que se realizará
              un aplicativo web para <span className="text-teal-500">Carnaval S.A.S</span> y mi rol es el lider del proyecto y desarrollador backend.
              
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
